/**
 * Autonomy Types Module
 * Phase 11 — Advanced Autonomy, Failure Recovery & Dynamic Replanning
 *
 * Defines high-level autonomy states, failure classifications, and recovery constraints.
 */

export const AUTONOMY_STATES = {
  IDLE: 'IDLE',
  EXECUTING: 'EXECUTING',
  MONITORING: 'MONITORING',
  RECOVERING: 'RECOVERING',
  REPLANNING: 'REPLANNING',
  WAITING_FOR_USER: 'WAITING_FOR_USER',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

export const FAILURE_CATEGORIES = {
  NO_TARGET: 'NO_TARGET',
  TARGET_UNREACHABLE: 'TARGET_UNREACHABLE',
  NAVIGATION_FAILED: 'NAVIGATION_FAILED',
  TARGET_DISAPPEARED: 'TARGET_DISAPPEARED',
  SCENE_CHANGED: 'SCENE_CHANGED',
  INTERACTION_FAILED: 'INTERACTION_FAILED',
  REQUIRED_OBJECT_MISSING: 'REQUIRED_OBJECT_MISSING',
  INVALID_PLAN: 'INVALID_PLAN',
  TIMEOUT: 'TIMEOUT',
  USER_CANCELLED: 'USER_CANCELLED',
  UNKNOWN_FAILURE: 'UNKNOWN_FAILURE',
};

export const AUTONOMY_EVENTS = {
  AUTONOMY_STARTED: 'AUTONOMY_STARTED',
  AUTONOMY_MONITORING: 'AUTONOMY_MONITORING',
  AUTONOMY_FAILURE_DETECTED: 'AUTONOMY_FAILURE_DETECTED',
  AUTONOMY_RECOVERY_STARTED: 'AUTONOMY_RECOVERY_STARTED',
  AUTONOMY_REPLANNING_STARTED: 'AUTONOMY_REPLANNING_STARTED',
  AUTONOMY_REPLAN_SUCCESS: 'AUTONOMY_REPLAN_SUCCESS',
  AUTONOMY_WAITING_USER: 'AUTONOMY_WAITING_USER',
  AUTONOMY_COMPLETED: 'AUTONOMY_COMPLETED',
  AUTONOMY_FAILED: 'AUTONOMY_FAILED',
  AUTONOMY_CANCELLED: 'AUTONOMY_CANCELLED',
};

export const MAX_RECOVERY_ATTEMPTS = 2;
